# Generated by Django 5.0.6 on 2024-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subtype', models.CharField(max_length=255)),
                ('Percentage', models.CharField(max_length=255)),
            ],
        ),
    ]
