# Generated by Django 5.0.6 on 2024-06-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADHD', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Patient',
        ),
    ]
