import { QrCode } from "lucide-react";

export const translations = {
  en: {
    currentTask: "Current Task",
    tasks: "Tasks",
    fillForm: "Form for Student",
    startTask: "Starting task",
    minutesLeft: "Minutes left",
    taskDeleted: "Task deleted successfully",
    allTasksCompleted: "All tasks completed! Great job!",
    today: "Today",
    howAreYouFeeling: "How are you feeling today?",
    viewRecommendations: "View recommendations",
    newAssessment: "Do a new assessment",
    myAssessments: "My assessments",
    helpSupport: "Help/support",
    feeling: "How am I feeling today?",
    noTaskSelected: "Please select a task first",
    search: "Search",
    minutes: "minutes",
    name: "Name",
    date: "Date",
    submit: "Submit",
    deleteTaskError: "Error deleting task",
    taskUpdatedSuccess: "Task updated successfully",
    taskUpdateError: "Error updating task",
    generalUpdateError: "General error in update",
    messageSentToTeacher: "Message sent to teacher",
    messageSendError: "Error sending message",
    noAssessmentAvailable:
      "No assessment available right now. Please contact your teacher",
    helpAndSupport: "Help and Support",
    writeYourMessage: "Write your message here on any topic you choose",
    whatWouldYouLike: "What would you like to ask or share?",
    cancel: "Cancel",
    send: "Send",
    timeUpForTask: "Time's up for task",

    child: {
      title: "Student Questionnaire",
      focus: "How well do you focus in class?",
      tired: "How tired do you feel during the day?",
      seat: "Does your seat help you focus?",
      food: "How do you feel about the school food?",
      physicalActivity: "Does physical activity help you feel better?",
    },

    none: "Not at all",
    little: "A little bit",
    sometimes: "Sometimes",
    most: "Most of the time",
    always: "All the time",
    moreDistracted: "No, I get distracted more",
    noDifference: "It makes no difference",
    helpsLittle: "It helps a little",
    helpsMuch: "It helps a lot",
    dislikeAll: "I don't like them at all",
    likeSome: "I like some of them",
    likeMost: "I like most of them",
    enjoyAll: "I enjoy them a lot",

    tasksList: {
      task1: "math homework Q1,2,3,4,8",
      task2: "Read & summarize a chapter from the book you are reading",
      task3:
        "Draw or paint a picture of your favorite scene from the book you are reading",
      task4: "Enjoy a healthy snack and hydrate",
      task5:
        "Watch a fun educational video related to this week's science topic",
      task6: "Write down three interesting facts you learned",
    },
  },

  he: {
    currentTask: "משימה נוכחית",
    tasks: "משימות",
    fillForm: "שאלון לתלמיד",
    startTask: "מתחיל משימה",
    minutesLeft: "דקות נותרו",
    taskDeleted: "המשימה נמחקה בהצלחה",
    allTasksCompleted: "כל המשימות הושלמו! כל הכבוד!",
    today: "היום",
    howAreYouFeeling: "איך אתה מרגיש היום?",
    viewRecommendations: "צפה בהמלצות",
    newAssessment: "בצע הערכה חדשה",
    myAssessments: "ההערכות שלי",
    helpSupport: "עזרה ותמיכה",
    feeling: "איך אני מרגיש היום?",
    noTaskSelected: "אנא בחר משימה",
    search: "חיפוש",
    minutes: "דקות",
    name: "שם",
    date: "תאריך",
    submit: "שלח",
    deleteTaskError: "שגיאה במחיקת משימה",
    taskUpdatedSuccess: "המשימה עודכנה בהצלחה",
    taskUpdateError: "שגיאה בעדכון המשימה",
    generalUpdateError: "שגיאה כללית בעדכון",
    messageSentToTeacher: "ההודעה נשלחה למורה",
    messageSendError: "שגיאה בשליחת ההודעה",
    noAssessmentAvailable: "אין אבחון זמין כרגע. אנא פנה למורה שלך",
    helpAndSupport: "עזרה ותמיכה",
    writeYourMessage: "כתוב את ההודעה שלך כאן בכל נושא שתבחר",
    whatWouldYouLike: "מה תרצה לשאול או לשתף?",
    cancel: "ביטול",
    send: "שלח",
    timeUpForTask: "הזמן נגמר למשימה",
    child: {
      title: "שאלון תלמיד",
      focus: "כמה אתה מצליח להתרכז בכיתה?",
      tired: "כמה אתה מרגיש עייף במהלך היום?",
      seat: "האם המקום שבו אתה יושב עוזר לך להתרכז?",
      food: "מה התחושה שלך לגבי האוכל בבית הספר?",
      physicalActivity: "עד כמה פעילות גופנית עוזרת לך להרגיש טוב יותר?",
    },

    none: "בכלל לא",
    little: "קצת",
    sometimes: "לפעמים",
    most: "רוב הזמן",
    always: "כל הזמן",
    moreDistracted: "לא, אני מוסח/ת יותר",
    noDifference: "זה לא משנה",
    helpsLittle: "זה עוזר קצת",
    helpsMuch: "זה עוזר הרבה",
    dislikeAll: "אני לא אוהב/ת אותם בכלל",
    likeSome: "אני אוהב/ת חלק מהם",
    likeMost: "אני אוהב/ת את רובם",
    enjoyAll: "אני נהנה/ית מהם מאוד",

    tasksList: {
      task1: "שיעורי בית במתמטיקה שאלות 1,2,3,4,8",
      task2: "קרא וסכם פרק מהספר שאתה קורא",
      task3: "צייר או צבע תמונה של הסצנה האהובה עליך מהספר שאתה קורא",
      task4: "תהנה מחטיף בריא ושתה מים",
      task5: "צפה בסרטון חינוכי מהנה הקשור לנושא המדע של השבוע",
      task6: "כתוב שלוש עובדות מעניינות שלמדת",
    },
  },
};

export interface ScheduleItem {
  time: string;
  subject: string;
  chapter: string;
  room: string;
  teacher: string;
}

export const scheduleItems: ScheduleItem[] = [
  {
    time: "13:15",
    subject: "Biology",
    chapter: "Chapter 3: Animal Kingdom",
    room: "Room S-305",
    teacher: "Julie Watson",
  },
  {
    time: "15:10",
    subject: "Geography",
    chapter: "Chapter 2: Knowing USA",
    room: "Room H-403",
    teacher: "Jenny Alexander",
  },
];

export const colorfulTasks = [
  {
    id: 1,
    title: "משחק שמיעה",
    minutes: 1,
    color: "#FBBF24",
    completed: false,
    stars: 2,
    category: "listening",
  },
  {
    id: 2,
    title: "סיכום פרק",
    minutes: 3,
    color: "#60A5FA",
    completed: false,
    stars: 3,
    category: "listening",
  },
  {
    id: 3,
    title: "תרגול מתמטי",
    minutes: 5,
    color: "#34D399",
    completed: false,
    stars: 1,
    category: "listening",
  },
];
